export const SET_ACTIVITYPLATFORMTEXT = 'SET_ACTIVITYPLATFORMTEXT'
export const SET_PLATFORMCATEGORYTEXT = 'SET_PLATFORMCATEGORYTEXT'
export const SET_ACTIVITYLEVELTEXT = 'SET_ACTIVITYLEVELTEXT'
export const SET_CONTROLLER_TEMPSTUDENTS = 'SET_CONTROLLER_TEMPSTUDENTS'
export const SET_ORGANIZER_TEMPSTUDENTS = 'SET_ORGANIZER_TEMPSTUDENTS'
export const SET_PARTICIPANT_TEMPSTUDENTS = 'SET_PARTICIPANT_TEMPSTUDENTS'
export const SET_TEMP_SPONSOR = 'SET_TEMP_SPONSOR'
export const SET_TEMP_CONTRACTOR = 'SET_TEMP_CONTRACTOR'
export const SET_TEMP_ASSIST = 'SET_TEMP_ASSIST'
export const SET_TEMP_SIGNPOSITION = 'SET_TEMP_SIGNPOSITION'
export const SET_TEMP_SIGN_START_TIME = 'SET_TEMP_SIGN_START_TIME'
export const SET_TEMP_SIGN_END_TIME = 'SET_TEMP_SIGN_END_TIME'
export const SET_TEMP_SIGNBACK = 'SET_TEMP_SIGNBACK'
export const SET_TEMP_SIGNTYPE = 'SET_TEMP_SIGNTYPE'
export const SET_TEMP_DURATION = 'SET_TEMP_DURATION'
export const SET_TEMP_COLLEGE = 'SET_TEMP_COLLEGE'
export const SET_TEMP_MAJOR = 'SET_TEMP_MAJOR'
export const SET_TEMP_GRADE = 'SET_TEMP_GRADE'
export const SET_TEMP_CLBUM = 'SET_TEMP_CLBUM'
export const SET_TEMP_OTHERCOLLEGE = 'SET_TEMP_OTHERCOLLEGE'
export const SET_TEMP_OTHERMAJOR = 'SET_TEMP_OTHERMAJOR'
export const SET_TEMP_OTHERGRADE = 'SET_TEMP_OTHERGRADE'
export const SET_TEMP_OTHERCLBUM = 'SET_TEMP_OTHERCLBUM'
export const SET_TEMP_LIMITCOLLEGE = 'SET_TEMP_LIMITCOLLEGE'
export const SET_TEMP_LIMITMAJOR = 'SET_TEMP_LIMITMAJOR'
export const SET_TEMP_LIMITGRADE = 'SET_TEMP_LIMITGRADE'
export const SET_TEMP_LIMITCLASS = 'SET_TEMP_LIMITCLASS'
export const SET_TEMP_CONTROLLER_SELECT = 'SET_TEMP_CONTROLLER_SELECT'
export const SET_TEMP_ORGANIZER_SELECT = 'SET_TEMP_ORGANIZER_SELECT'
export const SET_TEMP_PARTICIPANT_SELECT = 'SET_TEMP_PARTICIPANT_SELECT'

// BaseInfo
export const SET_ACTIVITYID = 'SET_ACTIVITYID' // 活动ID
export const SET_ACTIVITYCATETORY = 'SET_ACTIVITYCATETORY' // 活动类别
export const SET_ACTIVITYLEVEL = 'SET_ACTIVITYLEVEL' // 活动级别
export const SET_ACTIVITYATTRIBUTION = 'SET_ACTIVITYATTRIBUTION' // 活动归属
export const SET_ACTIVITYPLATFORM = 'SET_ACTIVITYPLATFORM' // 活动平台,平台类别
export const SET_ACTIVITYNAME = 'SET_ACTIVITYNAME' // 活动名称
export const SET_SLOGAN = 'SET_SLOGAN' // 活动口号
export const SET_ADDRESS = 'SET_ADDRESS' // 活动地址

export const SET_TEACHER = 'SET_TEACHER' // 教师(teacherId、teacherName、teacherPosition)

export const SET_COURSEDESCRIPTION = 'SET_COURSEDESCRIPTION' // 活动介绍
export const SET_COVERPICTURE = 'SET_COVERPICTURE' // 封面图片
export const SET_REMIND = 'SET_REMIND' // 提醒内容
export const SET_ACCESSORY = 'SET_ACCESSORY' // 附件
export const SET_REMARK = 'SET_REMARK' // 备注
export const SET_SPONSOR = 'SET_SPONSOR' // 主办方
export const SET_CONTRACTOR = 'SET_CONTRACTOR' // 承办方
export const SET_ASSIST = 'SET_ASSIST' // 协办方
export const SET_CHARGE = 'SET_CHARGE' // 咨询人

// RuleSetting
export const SET_ACTIVITYBEGINTIME = 'SET_ACTIVITYBEGINTIME' // 活动开始时间
export const SET_ACTIVITYENDTIME = 'SET_ACTIVITYENDTIME' // 活动结束时间
export const SET_APPLICATIONBEGINTIME = 'SET_APPLICATIONBEGINTIME' // 报名开始时间
export const SET_APPLICATIONENDTIME = 'SET_APPLICATIONENDTIME' // 报名结束时间
export const SET_ACTIVITYRETROACTIVE = 'SET_ACTIVITYRETROACTIVE' // 活动补签
export const SET_ACTIVITYRETROBEGINTIME = 'SET_ACTIVITYRETROBEGINTIME' // 活动补签开始时间
export const SET_ACTIVITYRETROENDTIME = 'SET_ACTIVITYRETROENDTIME' // 活动补签开始时间
export const SET_ACTIVITYCANCEL = 'SET_ACTIVITYCANCEL' // 活动取消
export const SET_ACTIVITYCANCELBEGINTIME = 'SET_ACTIVITYCANCELBEGINTIME' // 活动取消开始时间
export const SET_ACTIVITYCANCELENDTIME = 'SET_ACTIVITYCANCELENDTIME' // 活动取消结束时间
export const SET_ACTIVITIESLIST = 'SET_ACTIVITIESLIST' // 导入活动名单
export const SET_ACTIVITIELIST = 'SET_ACTIVITIELIST' // 活动名单
export const SET_ROLECANCEL = 'SET_ROLECANCEL' // 角色取消
export const SET_ROLECANCELBEGINTIME = 'SET_ROLECANCELBEGINTIME' // 角色取消开始时间
export const SET_ROLECANCELENDTIME = 'SET_ROLECANCELENDTIME' // 角色取消结束时间
export const SET_ACTIVITYCOMMENT = 'SET_ACTIVITYCOMMENT' // 活动评论
export const SET_COMMENTENDTIME = 'SET_COMMENTENDTIME' // 活动评论截至时间
export const SET_SIGNBACK = 'SET_SIGNBACK' // 签退
export const SET_SIGNCONTENT = 'SET_SIGNCONTENT' // 签到
export const SET_CONTROLLER = 'SET_CONTROLLER' // 管理者(controllerType,controller)
export const SET_ORGANIZER = 'SET_ORGANIZER' // 组织者(organizerType,organizer)
export const SET_PARTICIPANT = 'SET_PARTICIPANT' // 参与者(participantType,participant)

// ObjectSetting
export const SET_LIMITCOLLEGE = 'SET_LIMITCOLLEGE' // 不限学院
export const SET_LIMITMAJOR = 'SET_LIMITMAJOR' // 不限专业
export const SET_LIMITCLASS = 'SET_LIMITCLASS' // 不限班级
export const SET_LIMITGRADE = 'SET_LIMITGRADE' // 不限年级
export const SET_OTHERCOLLEGE = 'SET_OTHERCOLLEGE' // 其他学院
export const SET_OTHERMAJOR = 'SET_OTHERMAJOR' // 其他专业
export const SET_OTHERGRADE = 'SET_OTHERGRADE' // 其他年级
export const SET_OTHERCLASS = 'SET_OTHERCLASS' // 其他班级
export const SET_COLLEGE = 'SET_COLLEGE' // 学院
export const SET_MAJOR = 'SET_MAJOR' // 专业
export const SET_GRADE = 'SET_GRADE' // 年级
export const SET_CLBUM = 'SET_CLBUM' // 班级

export const SET_BASEINFO = 'SET_BASEINFO'
export const SET_RULESETTING = 'SET_RULESETTING'
export const SET_OBJECTSETTING = 'SET_OBJECTSETTING'
