<div class="demo-left-menu" id="leftmenu">

	<div class="panel-group">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" 
					   href="#collapseOne">
						模态框
					</a>
				</h4>
			</div>
			<div class="panel-collapse collapse">
				<ul class="list-group">
				  <li class="list-group-item"><a href="modal.html"><i class="glyphicon glyphicon-play"></i> 弹出</a></li>
				</ul>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" 
					   href="#collapseTwo">
						拖拽
					</a>
				</h4>
			</div>
			<div class="panel-collapse collapse">
				<ul class="list-group">
				  <li class="list-group-item"><a href="javascript://"><i class="glyphicon glyphicon-play"></i> default</a></li>
				</ul>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" 
					   href="#collapseTwo">
						表格
					</a>
				</h4>
			</div>
			<div class="panel-collapse collapse">
				<ul class="list-group">
				  <li class="list-group-item"><a href="table.html"><i class="glyphicon glyphicon-play"></i> 基础表格</a></li>
				</ul>
			</div>
		</div>
	</div>



</div>